### ISSUE TITLE
Failing to build on Ubuntu 19.04 with libclang properly installed

### ISSUE THREAD

**Issue by hawkinsw** [KyleMayes/clang-sys#104]
This is for others who may happen across the same problem: On an Ubuntu 19 installation with necessary libclang packages installed, the clang library is installed as `libclang.so.1`. The builder for clang-sys looks for a libclang that is named `libclang.so` or `libclang-*.so`. In either case, clang-sys is looking for so file whose extension is `.so`. That means that the one installed on such an Ubuntu 19 system will not be found. I was able to work around this problem by adding a symlink from libclang.so to libclang.so.1. After that, everything went according to plan. I hope this helps someone else in the future.

**Comment by KyleMayes** [comment]
Did you install the `libclang1` or `libclang-dev` package?

You can determine which `libclang`-related packages you have installed by running `dpkg -l | grep libclang`.

Using a clean Ubuntu 19.04 install, I don't get the symlink with the `libclang1` package but do get the `libclang.so` symlink with the `libclang-dev` package.
