### ISSUE TITLE
new clang-sys packages break against older versions

### ISSUE THREAD

**Issue by iximeow** [KyleMayes/clang-sys#114]
hi, sorry for the bad news! this applies both to the 0.29 and 0.28 packages, in slightly different ways:

in `0.28.1`, `CXCursorAndRangeVisitor`'s `visit` was [`extern "C" fn(_: *mut c_void, _: CXCursor, _: CXSourceRange) -> CXVisitorResult`](https://docs.rs/clang-sys/0.28.1/clang_sys/struct.CXCursorAndRangeVisitor.html), but in `0.28.2` that field turned into [`Option<extern "C" fn(*mut c_void, CXCursor, CXSourceRange) -> i32>`](https://docs.rs/clang-sys/0.28.2/clang_sys/struct.CXCursorAndRangeVisitor.html). since Cargo expects patch bumps of `0.y.z` versions to be compatible, this makes for breaking crate selections when building f.ex `clang`.

in `0.29.3`, `CXCursorAndRangeVisitor`'s `visit` was [`Option<extern "C" fn(_: *mut c_void, _: CXCursor, _: CXSourceRange) -> CXVisitorResult>`](https://docs.rs/clang-sys/0.29.3/clang_sys/struct.CXCursorAndRangeVisitor.html) but became [`Option<extern "C" fn(*mut c_void, CXCursor, CXSourceRange) -> i32>`](https://docs.rs/clang-sys/0.29.4/clang_sys/struct.CXCursorAndRangeVisitor.html) in `0.29.4`. The same breaking version selection issues apply here.

This showed up in at least two places - https://github.com/zombodb/pgx/issues/8#issuecomment-658067350 this issue, and an entirely unrelated build issue I was just tracking down :)

edit: for good measure I checked `0.27` as well - `0.27.0` -> `0.27.1` has the same breaking change as in `0.28.1` -> `0.28.2`

**Comment by iximeow** [comment]
ah, I see this relates to https://github.com/KyleMayes/clang-sys/issues/96 - a quick read has me suspecting that this means `clang-sys-linkage` is not as API-compatible as was discussed there?

**Comment by jrandall** [comment]
We've been bitten by this as well - bindgen 0.52.0 fails to build as of this morning with a bunch of errors such as:
```
error[E0433]: failed to resolve: use of undeclared type or module `clang_Cursor_getMangling`                                                                                                                                                                                                                                                                                                                                            
```

It is building against `v0.28.2` but it looks like bindgen requires an earlier version. It does look like this relates to #96, yes.

**Comment by lexxvir** [comment]
@jrandall Same here, see my issue in the bindgen repo https://github.com/rust-lang/rust-bindgen/issues/1827

**Comment by KyleMayes** [comment]
The offending versions have been yanked, things should be back to the way they were.
Sorry for the trouble, I did not realize there were API incompatibilities between `v0.27` and `v0.28`.
I guess that's what I get for trying to solve people's build problems, just cause a bunch more... 🤷‍♂️
