### ISSUE TITLE
Use target-prefixed binaries first when trying to find clang

### ISSUE THREAD

**Issue by s1341** [KyleMayes/clang-sys#125]
When searching for clang, with the `clang_sys::support::Clang::find` function, (here: https://github.com/KyleMayes/clang-sys/blob/master/src/support.rs#L69), clang-sys should prefer target-prefixed binaries over raw "clang" or "clang++" binaries.

Failure to do so causes cross-compilation to fail, in the case that the 'main' clang executables are not able to provide the specified target.

I'm happy to prepare a PR for this if necessary. CC @ericson2314

**Comment by KyleMayes** [comment]
Providing a PR might be necessary, because I'm not sure what these target-prefixed `clang` binaries are, are they only available when building multiple targets from source?

And when you say to prefer target-prefixed binaries, do you mean for the current platform? Or for a specific platform since you mention cross-compilation?

**Comment by s1341** [comment]
I mean that if you are cross-compiling for aarch64-linux-android, using `cargo build --target=aarch64-linux-android`, then clang-sys should look for the binary `aarch64-linux-android-clang` (or perhaps `aarch64-unknown-linux-clang`) instead of just `clang`.

So far as I know, you can determine this from the `-target` argument passed as a clang argument to the find function.

**Comment by KyleMayes** [comment]
OK that sounds doable, but is there a list of these targets and the alternatives such as the `aarch64-unknown-linux` as an alternate for `aarch64-linux-android`?

I have never worked with cross-compilation before so I have no idea what I'm doing here 😄

**Comment by s1341** [comment]
Well. You can see a list of targets using `rustc --print target-list`.

I don't really know of any 'alternates' other than the aarch64-unknown-linux-android one. I suggest we start with respecting the `-target` argument, and add special cases as necessary.

**Comment by KyleMayes** [comment]
This has been implemented in `1.2.0`.

I did some testing with dummy executables and it seems to work fine, but I don't have a real cross-compilation toolchain set up so I'm not 100% it works as you want it to. If you run into any problems, please reopen this issue or open a new one.

**Comment by s1341** [comment]
Awesome! Thanks! I'll test it and let you know.
