### ISSUE TITLE
Mac build broken

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#13]
https://travis-ci.org/crabtw/rust-bindgen/jobs/129245610

**Comment by Yamakaky** [comment]
Especaly, build.rs seems to output `-l dylib=:libclang.dylib`. I think it should be `-l dylib=libclang.dylib`

**Comment by KyleMayes** [comment]
OK, I'm working on OS X builds in Travis right now.

**Comment by Yamakaky** [comment]
`:` doesn't seem to be the problem, on linux at least, since the linking fails without it.

**Comment by Yamakaky** [comment]
hint: maybe it should be `framework` instead of `dylib` on build.rs:126

**Comment by Yamakaky** [comment]
Also, linking errors will not be detected by cargo build on this crate, it must build a bin.

**Comment by KyleMayes** [comment]
OK, I'm testing a solution. It'll be a while because OS X VMs take forever to start up on Travis CI.

**Comment by KyleMayes** [comment]
OK, I have a solution, testing it on Windows now.

**Comment by KyleMayes** [comment]
OK, this should be fixed.

**Comment by Yamakaky** [comment]
\o/
