### ISSUE TITLE
LIBCLANG_PATH cannot contain special characters such as `[` or `]`

### ISSUE THREAD

**Issue by sunpeaksfivemile** [KyleMayes/clang-sys#133]
When LIBCLANG_PATH is set to a path that contains `[` libclang cannot be found. 

I believe it is because the path is interpreted as a glob here https://github.com/KyleMayes/clang-sys/blob/20a95da7955cf6662006972351f06f8d064eaaff/build/common.rs#L169

**Comment by KyleMayes** [comment]
Fixed in `v1.2.2`.
