### ISSUE TITLE
No `clang_getToken` binding in clang-sys

### ISSUE THREAD

**Issue by yingmanwumen** [KyleMayes/clang-sys#139]
I am a beginner of `LLVM`, and writing some toy code by following C++ code.
There is a C interface in `libclang` named `clang_getToken`, and the prototype of it is
```c
CXToken* clang_getToken(CXTranslationUnit TU, CXSourceLocation | Location);
```
But I didn't find the corresponding binding in `clang-sys`.
Is that a neglect or a deliberation? Thanks.

**Comment by KyleMayes** [comment]
Missed this function by mistake.
Added in `v1.3.1`.
