### ISSUE TITLE
Detect LLVM installation directory in visual studio on Windows

### ISSUE THREAD

**Issue by ikey4u** [KyleMayes/clang-sys#166]
Hi! As @perqin  mentioned here [https://github.com/KyleMayes/clang-sys/issues/121](https://github.com/KyleMayes/clang-sys/issues/121), visual studio does install Llvm into directory like
```
C:\Program Files*\Microsoft Visual Studio\*\VC\Tools\Llvm
```
And this path is mentioned in visual studio document [here](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#configure-a-windows-project-to-use-clang-tools):

> It links with the Microsoft implementation of the Standard Library. By default, clang-cl.exe is located in %VCINSTALLDIR%\Tools\Llvm\bin\ and %VCINSTALLDIR%\Tools\Llvm\x64\bin\.

If you think it's alright, I would be happy to submit a patch and assist with related testing.

**Comment by KyleMayes** [comment]
I've released `v1.8.1` which removed `BuildTools` from the search path for Visual Studio (see above referenced commit), so it should be better at detecting `libclang` in this case.
