### ISSUE TITLE
Support LLVM libc++

### ISSUE THREAD

**Issue by theoparis** [KyleMayes/clang-sys#168]
Bindgen fails  to build due to the following line. I use libc++ and it tries to link against libstdc++.

https://github.com/KyleMayes/clang-sys/blob/f76ca0660206f2d4a25ec063fb49e77920b68f4a/build/static.rs#L132

**Comment by KyleMayes** [comment]
I added a `libcpp` Cargo feature that enables linking to `libc++` instead of `libstd++` on Linux / Haiku.
This has just been released in `v1.8.0`.
