### ISSUE TITLE
Travis build of bindgen

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#17]
Maybe we don't need [so many builds](https://travis-ci.org/crabtw/rust-bindgen/builds/132369056) for bindgen since you also use travis? Do you also test static link?
What do you think?

**Comment by KyleMayes** [comment]
You probably don't, the builds in this repository should cover all the bases, and the test builds for [clang-rs](https://github.com/KyleMayes/clang-rs) are even more exhaustive.
