### ISSUE TITLE
Static linking doesn't work

### ISSUE THREAD

**Issue by theoparis** [KyleMayes/clang-sys#174]
```
Caused by:
  process didn't exit successfully: `/home/theo/dev/raknet/target/debug/build/clang-sys-6b084d6bff3d9148/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/theo/.cargo/git/checkouts/clang-sys-67ca2c90881f88fe/ab99460/build/static.rs:90:9:
  could not find any static libraries
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

After I fixed #168 in my fork, I realized clang-sys tries to find libclang.a which doesn't exist. Instead it should be using all of the clang libraries (`libclang*.a`, not a singular `libclang.a`)

**Comment by theoparis** [comment]
Is this library being maintained anymore? I am still encountering my two issues and this breaks the entire rust ecosystem on my end - meaning everything that relies on bindgen is unusable.

**Comment by KyleMayes** [comment]
I'm pretty sure static linking only works when `libclang.a` is available, but this isn't included in most builds.
(e.g., `sudo apt install libclang-dev` on Ubuntu won't include `libclang.a`).

I'm looking into building `libclang.a` from source and seeing if static linking still works with that approach.

**Comment by theoparis** [comment]
Yeah, I did try using clang built from source but maybe I missed a cmake option to build everything as a single libclang.a file, not sure. Currently I have a `libclang.so` and a bunch of libclangXYZ.a libraries.

**Comment by KyleMayes** [comment]
Looks like you need to turn the `LIBCLANG_BUILD_STATIC` option on:
https://github.com/llvm/llvm-project/blob/cbd8031baa62f20d8513f084104180f9d49d763d/clang/tools/libclang/CMakeLists.txt#L87-L88

And have PIC disabled:
https://github.com/llvm/llvm-project/blob/cbd8031baa62f20d8513f084104180f9d49d763d/clang/tools/libclang/CMakeLists.txt#L118-L120

**Comment by KyleMayes** [comment]
This worked for me (in a freshly cloned `llvm-project` repo):

```
cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DLIBCLANG_BUILD_STATIC=ON
ninja -C build
```

That (eventually) produced `build/lib/libclang.a`.

Then, after setting the `LLVM_CONFIG_PATH` environment variable to point to the newly built `llvm-config`, I was able to run `cargo test --features static` in `clang-sys` with no issues.

(Note: It was taking ages to link the zillions of LLVM/Clang static libraries until I switched to nightly Rust which uses `lld` instead of `ld` for linking)

**Comment by KyleMayes** [comment]
I've updated the error message for when static linking fails to find `libclang.a` and added a section to the README about how most users will probably need to build `libclang.a` themselves since it usually isn't included in most distributions of LLVM / Clang.
