### ISSUE TITLE
clang-sys looks for a "-target" flag to determine the cross-compilation target, but the flag is actually called "--target"

### ISSUE THREAD

**Issue by DrTobe** [KyleMayes/clang-sys#175]
In the `find()` method, the arguments slice is checked for an argument `-target`. `clang --help` says that the flag is actually named `--target`:

https://github.com/KyleMayes/clang-sys/blob/99f4007e0b304631850f34cc1be89ac74f593ab8/src/support.rs#L71

I stumbled over this when I was debugging my own setup and I guess this is wrong, but I am not 100% sure (maybe, this changed between clang versions? mine is 17.0.6). Should I open a PR? Frankly speaking, handling the PR seems to be as much work for you as quickly fixing it yourself, so you could also do it yourself.

**Comment by KyleMayes** [comment]
Looks like `--target` is the "correct" way to specify this argument, but the `clang` executable is fairly permissive here and also supports `-target`, so I'll update it to support both `-target` and `--target`.

**Comment by KyleMayes** [comment]
Fix released in `v1.8.0`.

**Comment by DrTobe** [comment]
> but the clang executable is fairly permissive here and also supports `-target`

My clang complained, otherwise I would not have found this I guess. So it is good to have this fixed, thanks!
