### ISSUE TITLE
Merge the clang.rs file from bindgen into clang-sys

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#19]
It would be more useful here. What do you think?

**Comment by KyleMayes** [comment]
Well this crate is just the raw bindings and finding the libraries, [clang-rs](https://github.com/KyleMayes/clang-rs) provides the wrapper.

**Comment by Yamakaky** [comment]
(please don't insta-close the issues ;)

Wow, I forgot the existence of this crate. Maybe the best thing to do would be for bindgen to use it.
