### ISSUE TITLE
Add a get_include_dir function

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#20]
Clang doesn't have a reliable builtin method to get the include directory for system headers. A better [`get_include_dir`](https://github.com/crabtw/rust-bindgen/blob/master/src/lib.rs#L329) could be included in your crate.
https://github.com/crabtw/rust-bindgen/issues/317

**Comment by KyleMayes** [comment]
This functionality was added by 3797e5cd46cffa13060e39845f65b7db36d30d22.

**Comment by KyleMayes** [comment]
Also, I tested it on Windows.

**Comment by Yamakaky** [comment]
Cool!
