### ISSUE TITLE
parse_version fails on debian Jessie

### ISSUE THREAD

**Issue by ousado** [KyleMayes/clang-sys#25]
running the rust-bindgen tests, which uses cargo-sys
---- builder_state stdout ----
        thread 'builder_state' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', ../src/libcore/result.rs
... 
  17:     0x559314b80437 - clang_sys::support::parse_version::h797e147fe3900f18
                        at /clean/devenv/rust/cargo/registry/src/github.com-88ac128001ac3a9a/clang-sys-0.6.0/src/support.rs:89
  18:     0x559314b7fea5 - clang_sys::support::Clang::new::hdc3ebf8b18e7e1ba
                        at /clean/devenv/rust/cargo/registry/src/github.com-88ac128001ac3a9a/clang-sys-0.6.0/src/support.rs:32
....

clang --version on this system outputs:
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)

**Comment by ousado** [comment]
I would be nice to be able to specify the version independently, via an environment variable for instance

**Comment by KyleMayes** [comment]
I knew it was a terrible decision to use `unwrap`, but I did it anyway. I'll improve the version parsing and remove the usage of `unwrap` so it doesn't crash in the future.

But what do mean about specifying the version? Do you mean specifying which version is linked to when building the crate? Because that is handled (somewhat) by the `LLVM_CONFIG_PATH` and `LIBCLANG_PATH` environment variables.

**Comment by ousado** [comment]
KyleMayes - well, in this case I had to clone and override the crate to make it work for me, so I thought being able to pass in e.g.  CLANG_SYS_CLANG_VERSION="3.5.0" or something would be a good idea, since distros seem to mess with the --version output, making it unpredictable

**Comment by KyleMayes** [comment]
The reported version isn't really reliable in any case, so I improved the version parsing and made it optional (if the parsing fails, it won't crash) in 5cc4585920434fdea62a8f59a2ede320e2ddb30d.
