### ISSUE TITLE
Add DYLD_LIBRARY_PATH to the README

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#26]
https://github.com/crabtw/rust-bindgen/blob/2b7143317227107adc1186e34a027fa1ad625b39/README.md#building
You should add it to your readme, maybe also with a mention to LD_LIBRARY_PATH, maybe.

**Comment by KyleMayes** [comment]
Added by 277a451947d49e11ee12219867ad5e7037a0b24e.

**Comment by Yamakaky** [comment]
Cool
