### ISSUE TITLE
Can't find clang on Ubuntu

### ISSUE THREAD

**Issue by jethrogb** [KyleMayes/clang-sys#28]
On Ubuntu, LLVM binaries have the version number appended to their name, like so:
```
$clang[TAB][TAB]
clang-3.5                     clang-format-diff-3.5
clang++-3.5                   clang-modernize-3.5
clang-apply-replacements-3.5  clang-query-3.5
clang-check-3.5               clang-tblgen-3.5
clang-format-3.5              clang-tidy-3.5
```
`support::Clang::find` can't find clang this way.

**Comment by KyleMayes** [comment]
Should be fixed by 1ef7a4fe0ec93c160e01e5da0fb0ea20a44185fd.

**Comment by tatref** [comment]
Same issue here on Debian 8.5.

The clang lib is `/usr/lib/llvm-3.5/lib/libclang.so.1`, but I had to create a link named `libclang.so` to get it to compile.

Error message follow:
```
Build failed, waiting for other jobs to finish...
error: failed to compile `bindgen v0.18.0`, intermediate artifacts can be found at `/tmp/cargo-install.7B4EzkrL0K9o`

Caused by:
  failed to run custom build command for `clang-sys v0.7.2`
process didn't exit successfully: `/tmp/cargo-install.7B4EzkrL0K9o/release/build/clang-sys-66118395f506ca26/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'could not find libclang.so, set the LIBCLANG_PATH environment variable to a path where libclang.so can be found', /home/tatref/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.7.2/build.rs:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It seems that the version I'm using should be clear of this bug?

**Comment by KyleMayes** [comment]
This issue was for finding the clang executable when it had a version number appended to it (e.g., `clang-3.5`), not the `.so`. Could you open a separate issue with what behavior you expect so I don't forget to Fox this? 

Thanks.
