### ISSUE TITLE
Missing comment functions

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#35]
http://clang.llvm.org/doxygen/group__CINDEX__COMMENT.html
Notably clang_HTMLTagComment_getTagName

**Comment by KyleMayes** [comment]
Working on it now. Luckily they haven't changed since 3.5, so it will be easy to add them.

**Comment by Yamakaky** [comment]
Cool, thx.

**Comment by KyleMayes** [comment]
`v0.9.0` has been published with the documentation bindings.

**Comment by Yamakaky** [comment]
Cool!
