### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#36]
If I compile with clang_3_9, does the build script checks if clang 3.9 is available?

**Comment by KyleMayes** [comment]
No. There isn't a reliable way to parse `clang --version` as it differs from platform to platform, so I didn't even try.

However, now that I think about it, there may be a better way. You get linking errors if you attempt to call a clang 3.9 function but have linked to an earlier version of clang, so I could detect the version of clang in use by attempting to compile a program using non-3.5 features in `build.rs`, I'll look into it soon.

**Comment by Yamakaky** [comment]
I also think that would be more reliable (it compiles or not ^^).

**Comment by KyleMayes** [comment]
I've actually gone an implemented this, but now that I've thought about it more I don't think it adds much. You will find out if your version of clang is insufficient when to attempt to use a function that your version of clang does not support by way of a link error. This would cause the failure to be one step earlier, but at the risk of added complexity and false positives.

**Comment by Yamakaky** [comment]
That was mostly to add better error messages.
