### ISSUE TITLE
Use enum_primitive

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#37]
It would easier to convert from the c types to the rust enums.
https://github.com/andersk/enum_primitive-rs

**Comment by KyleMayes** [comment]
You shouldn't ever need to convert from the C types to Rust types though, the library does that automatically. What are you doing that you need to do something like this (e.g., convert `c_int`s to `CXCursorKind`s)?

**Comment by Yamakaky** [comment]
`http://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga027abe334546e80931905f31399d0a8b` can return an error.

**Comment by KyleMayes** [comment]
`enum_primitive` doesn't seem to support conditional variants (i.e., enabled by a `cfg` attribute). I'll try to come up with something that does.

**Comment by Yamakaky** [comment]
Cool, thx

**Comment by KyleMayes** [comment]
Well, writing a macro to handle both enums that are conditional as well as enums that contain conditional variants ended up being qutie complicated. Instead, I just added a `from_raw` method to `CXTypeLayoutError` as it seems to be the only enum that one would need this conversion for.

**Comment by Yamakaky** [comment]
Cool, thanks
