### ISSUE TITLE
Proposal: Load libclang on runtime

### ISSUE THREAD

**Issue by jeandudey** [KyleMayes/clang-sys#38]
Some users like me can't get working `clang-sys` linking to libclang and the only way to get it working was loading it dynamically using `dlopen` and it's friends, we could mantain two versions of the library like [x11-rs](https://github.com/Daggerbot/x11-rs) does, one linked (x11) and one loading the library at runtime (x11-dl).

Sorry if my english isn't good, i speak spanish :)

**Comment by KyleMayes** [comment]
I don't think two separate versions are necessary, I think a Cargo feature would work.

Something like `cargo build --features dl` would build `clang-sys` without linking to `libclang`, and would enable runtime linking with `dlopen`. I'll look into it.

And your English is fine.

**Comment by KyleMayes** [comment]
I've added support for loading `libclang` functions at runtime in the [`runtime`](https://github.com/KyleMayes/clang-sys/tree/runtime) branch if you enable the `runtime` cargo feature (e.g., `cargo test --features runtime`). The relevant functions are [`clang_sys::load`](https://github.com/KyleMayes/clang-sys/blob/911e82e8f2d084ef41832c18a0e383e048488c91/src/link.rs#L94-L116) and [`clang_sys::unload`](https://github.com/KyleMayes/clang-sys/blob/911e82e8f2d084ef41832c18a0e383e048488c91/src/link.rs#L123-L135). Could you clone this branch and test that it meets your needs?

**Comment by jeandudey** [comment]
Seems good!. :+1:

**Comment by Yamakaky** [comment]
Cool!

**Comment by KyleMayes** [comment]
Released as part of `v0.10.0`.
