### ISSUE TITLE
dyld: Library not loaded: @rpath/libclang.dylib

### ISSUE THREAD

**Issue by philippkeller** [KyleMayes/clang-sys#41]
Building bindgen on my OS X (Yosemite) all works fine but once I execute it:

```
> target/debug/bindgen
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Users/philipp/local.ch/rust-bindgen/target/debug/bindgen
  Reason: image not found
Trace/BPT trap: 5
```

my libclang.dylib is here: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib`

and `xcode-select -p` outputs `/Applications/Xcode.app/Contents/Developer`, so all seems fine. Any hints?

**Comment by KyleMayes** [comment]
I think you may need to set the `DYLD_LIBRARY_PATH` environment variable to the directory in which `libclang.dylib` can be found so that `dyld` can find the `dylib` at runtime.

**Comment by philippkeller** [comment]
thank you. Indeed and export solves it:

```
export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
```

Might be that somehow brew (or me trying to clean up) removed some symlinks in `/usr/lib` but as OS X doesn't let you ln -s in /usr/lib the only way seems to be to add the export statement into `.bash_profile`
