### ISSUE TITLE
Non informative error message when libclang is 32 bits

### ISSUE THREAD

**Issue by dbrodie** [KyleMayes/clang-sys#48]
On fedora the `load_manually` function looks for clang in /usr/lib instead of /usr/lib64 which makes the ELF not load. Instead of getting the error message:
`wrong ELF class: ELFCLASS32`
You get the unhelpful message:
`the ``libclang`` shared library could not be opened`.

rustc version:
`rustc 1.17.0-nightly (0f34b532a 2017-02-21)
binary: rustc
commit-hash: 0f34b532af590d25e9178f87c620931dd671cc2e
commit-date: 2017-02-21
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9`

**Comment by KyleMayes** [comment]
`v0.15.0` has been released with this fixed.
