### ISSUE TITLE
On fedora clang-sys finds the 32 bit version of libclang

### ISSUE THREAD

**Issue by dbrodie** [KyleMayes/clang-sys#49]
on fedora, clang-sys should look first in the /usr/lib64 directory if it is a 64 bit binary. Currently it looks in the /usr/lib directory which contains the 32 bit versions of the library. This causes error #48.

**Comment by KyleMayes** [comment]
Could you clone the [`fedora`](https://github.com/KyleMayes/clang-sys/tree/fedora) branch and see if the changes made fixes this?

The build script now rejects dynamic libraries that have an ELF header for the wrong architecture and the error message has been improved to include rejected libraries.

**Comment by dbrodie** [comment]
Yup, fedora branch works great!

Thanks!

**Comment by KyleMayes** [comment]
Great!

I've been holding off on releasing a new version until Clang 4.0 is released, hopefully that happens soon so these changes (among others) can be released.

**Comment by KyleMayes** [comment]
`v0.15.0` has been released with this fixed.
