### ISSUE TITLE
custom static build fails, because build uses llvm-config --libs without using --libdir

### ISSUE THREAD

**Issue by pornel** [KyleMayes/clang-sys#50]
I built static llvm and clang, and did `make install` to custom, non-standard directories.

Static `build.rs` of clang-sys `get_llvm_libraries()` only queries `llvm-config --libs`, but this output just lists lib names (`-lLLVMLTO -lLLVMPasses`) and lacks any `-L` flags required to find them.

This fixes the build for me:

```rust
print!("-L {} ", run_llvm_config(&["--libdir"]).expect("libdir"));
```

**Comment by KyleMayes** [comment]
The build script assumed that `libclang.a` and the other Clang static libraries are in the same directory as the LLVM static libraries, I'm guessing that's not the case for your custom build.

Could you test the `llvm-static` branch? Thanks.

**Comment by pornel** [comment]
Yes, it builds now. Thank you.

**Comment by KyleMayes** [comment]
`v0.15.1` has been released with this fix.
