### ISSUE TITLE
thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments on travis-ci

### ISSUE THREAD

**Issue by zzeroo** [KyleMayes/clang-sys#52]
Not sure what's happen here. The build on my local machine works fine. But on [travis-ci.org](https://travis-ci.org/zzeroo/modbus-rs) I get this error: 
* https://api.travis-ci.org/jobs/227893001/log.txt?deansi=true

**Comment by KyleMayes** [comment]
The version of Clang available on Travis CI by default is 3.4. Based on your [.travis.yml](https://github.com/zzeroo/modbus-rs/blob/468d2c82570b688b2564f2d60d3c214f1b3dc0f3/.travis.yml), you are not installing Clang 3.9, which is necessary for `bindgen`.

Checkout the [.travis.yml](https://github.com/KyleMayes/clang-sys/blob/87b674e9274c50995a6a4601e1160165490cb0e7/.travis.yml) for this project for an example of how to install a version of Clang on Travis CI.
