### ISSUE TITLE
`support::parse_search_paths()` should not `.expect(include_start)`

### ISSUE THREAD

**Issue by yoanlcq** [KyleMayes/clang-sys#54]
*(The title refers to [https://github.com/KyleMayes/clang-sys/blob/master/src/support.rs#L185](https://github.com/KyleMayes/clang-sys/blob/master/src/support.rs#L185))*  

It's as the title says - To give more context, I ran into a panic caused by this when using `bindgen` and it took me a while to figure out that it was because my `clang` is the one provided by Emscripten 1.37 which, unlike the "regular" `clang`, only outputs the "`#include "[...]" search starts here:`" line but not the "`#include <[...]> search starts here:`" one.  

Also, seeing only that line as the message I got from the resulting panic was confusing to me.  

I suggest that, instead of panicking, an empty Vec be returned.

**Comment by KyleMayes** [comment]
I changed the include search paths to be stored as `Option<Vec<PathBuf>>`. They are `None` if the parsing fails for some reason.

Released as part of `v0.17.0`.
