### ISSUE TITLE
Expose location of C headers

### ISSUE THREAD

**Issue by pornel** [KyleMayes/clang-sys#58]
For my project I need to compile a bit of extra C code that uses clang functions.

However, in my build script I'm unable to find the right directory that contains the headers.

Could you expose that information? It's usually done by setting [links](http://doc.crates.io/build-script.html#the-links-manifest-key) and emitting Cargo variable `cargo:include=`, so that other build scripts can find it via `DEP_CLANG_INCLUDE` env var.

I can make a PR if you're interested.

**Comment by KyleMayes** [comment]
Would something like [this](https://github.com/KyleMayes/clang-sys/commit/ab0cbf4dbbe4ce090f2b5dba217210470c24d8c0) be sufficient?
Or would a search of all the likely places (e.g., `/usr/local/include`) for a `clang-c` directory be necessary?

**Comment by pornel** [comment]
Thank you for adding this. It's a good direction, but not sufficient.

In my case, I need to include files such as "clang/AST/OperationKinds.h" and "llvm/Support/DataTypes.h" (from `…/llvm/include` and `…/clang/include`). That's because the libclang C API is incomplete, so I'm using the C++ API (in static build) to fill the gaps.

Exposing just the root `--includedir` would be better (or maybe both using [join](https://doc.rust-lang.org/std/env/fn.join_paths.html)?)

I also need path of clang include dir. I see it's tougher to get it in the build.rs.
