### ISSUE TITLE
Is LIBCLANG_STATIC really useful?

### ISSUE THREAD

**Issue by Yamakaky** [KyleMayes/clang-sys#6]
since you can use the cargo feature.
cc @nox

**Comment by KyleMayes** [comment]
I dunno, it was in `rust-bindgen`s `build.rs`, I assumed someone somewhere had requested it at some point. I don't think its existence should bother anyone.

**Comment by KyleMayes** [comment]
Removed by 97402000f4cfd2f4693c972f274e227252760395.
