### ISSUE TITLE
Versioned libclang.so on Ubuntu

### ISSUE THREAD

**Issue by ahti** [KyleMayes/clang-sys#68]
On Ubuntu 16.04, the clang packages (at least libclang-3.9-dev) don't contain libclang.so, but only a versioned shared library. This versioned library is called libclang-3.9.so. It might be useful to, in addition to searching for versioned libs that have the version appended, also search for the Ubuntu-style versioned library.

**Comment by KyleMayes** [comment]
Support for finding libraries in the format `libclang-${VERSION}.so` has been added in `v0.21.1`.
