### ISSUE TITLE
search LD_LIBRARY_PATH for libclang

### ISSUE THREAD

**Issue by ahti** [KyleMayes/clang-sys#71]
I'm trying to use ffmpeg-sys (which depends on bindgen and thus clang-sys) in a Heroku-like environment. In that environment, apt packages (using heroku-buildpack-apt) are not installed in their default location, but in another user-writable directory. LD_LIBRARY_PATH is set so the folder where libclang-3.9.so (in my case) can be found is included.

I think it would be sensible to include all directories in LD_LIBRARY_PATH in the locations searched for the libclang shared library. This would happen automatically if clang-sys were linked with libclang in the normal way, so I think it would be sensible to match that behaviour when loading the library at runtime.

**Comment by nox** [comment]
> You can temporarily substitute a different library for this particular execution. In Linux, the environment variable `LD_LIBRARY_PATH` is a colon-separated set of directories where libraries should be searched for first, before the standard set of directories; this is useful when debugging a new library or using a nonstandard library for special purposes.

Is there any documentation somewhere about how Heroku-like environments make use of that environment variable?

**Comment by ahti** [comment]
In my case, `LD_LIBRARY_PATH` is set through both [`.profile.d`-scripts](https://devcenter.heroku.com/articles/buildpack-api#profile-d-scripts) and the [`export` file](https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks), by [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt), to include paths where APT packages libraries are installed.

Binaries using dynamically linked libraries will pick up shared libraries in those directories in addition to those installed in system paths. Since clang-sys dloads libclang itself, without traditional dynamic linking, it would need to searth those paths itself to match that behaviour.

**Comment by KyleMayes** [comment]
This seems reasonable, I will add this when I get a chance.

**Comment by KyleMayes** [comment]
This has (finally) been released as part of `v0.21.2`.
