### ISSUE TITLE
Support for clang 8.0

### ISSUE THREAD

**Issue by michaelwu** [KyleMayes/clang-sys#76]
I know it's a bit early, but I need some features that landed right after clang 7.0 branched. Here's my code in case you're interested https://github.com/michaelwu/clang-sys/tree/clang-8.0 .

**Comment by KyleMayes** [comment]
I would prefer not to release support for Clang 8 until it has been released (or at least until it has been finalized and they start releasing release candidates).

However, I will gladly add your code as a branch here when I get a chance.

Thanks!

**Comment by KyleMayes** [comment]
Released in `v0.28.0`.
