### ISSUE TITLE
Allow for non-standard clang install paths on macOS

### ISSUE THREAD

**Issue by aaronsky** [KyleMayes/clang-sys#78]
I just ran into an issue with coreaudio-sys by way of rust-bindgen by way of clang-sys where it was not able to find the path to my libclang.dylib. 

I managed to pin it down to [this](https://github.com/KyleMayes/clang-sys/blob/master/build.rs#L266) line, where the shared library search path points to a typical Xcode installation location. However, I'm a Cocoa dev who bounces around between Xcode versions a lot and have to maintain a folder structure for managing different Xcode versions in different locations. This path being hardcoded, alongside the fact that I can't get RLS to account for environment variables and I don't have my own version of LLVM installed, has left me with limited options here.

Instead of hardcoding this path, can we change this behavior to do a search based on the return from `xcode-select -p`? I see that we're already checking for some output from xcodebuild to find the clang executable, so it wouldn't be antithetical to the design of the rest of the crate.

**Comment by aaronsky** [comment]
Also, for anyone else who runs into this through Google, the short-term workaround I'm using is to create a symbolic link to my Xcode.app and updating that manually when necessary. Definitely not ideal.

`ln -s /Applications/Xcode/9F1027a/Xcode.app /Applications/Xcode.app

**Comment by KyleMayes** [comment]
Searching the directory returned by `xcode-select -p` seems like a reasonable addition for macOS, I will look into it.

Also, is that folder structure something commonly used by people with multiple Xcode installs, or is it something you have setup?

A second line of defense might be adding `/Applications/Xcode/*/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib`
as a search path in addition to querying `xcode-select`.

**Comment by aaronsky** [comment]
This particular pattern is my own thing, since I usually have several versions of Xcode installed. Some folks just have an Xcode.app and an Xcode-beta.app in `/Applications`, some put it in `~/Applications`, and a number of others use the conventions set by the [xcode_install](https://github.com/KrauseFx/xcode-install) gem. In all those cases, `xcode-select` should be sufficient to get the active Xcode path.

Thanks for the fast reply!

**Comment by KyleMayes** [comment]
Could you please test the `xcode` branch for me?

I don't have access to macOS so I cannot test it myself.

The relevant code is [here](https://github.com/KyleMayes/clang-sys/blob/b82d1329f1589c5d8726d8898ef7acb6170790f8/build/common.rs#L101-L108).

**Comment by aaronsky** [comment]
I will test momentarily, but looking at the change, you can safely remove the `Contents/Developer/` at the beginning of the joined path string. When I run `xcode-select --print-path` locally, I get `/Applications/Xcode/10L232m/Xcode-beta.app/Contents/Developer`

**Comment by KyleMayes** [comment]
For some reason I thought that the documentation I was looking at omitted that part of the directory, but now looking again I see that it does not.

I have pushed a change to the `xcode` branch that should now hopefully work.

**Comment by KyleMayes** [comment]
Released as part of `v0.24.0`.
