### ISSUE TITLE
Support minimum version

### ISSUE THREAD

**Issue by jdm** [KyleMayes/clang-sys#79]
It would be useful for cases where we require a certain minimum version of clang to be used to provide an error if that version can't be found.

**Comment by KyleMayes** [comment]
Do you mean something like if `clang-sys` is a dependency with the features `clang_6_0` and `minimum_version` (or another name) and a `libclang` library with a version in the filename not greater than or equal to the requested version (e.g., `libclang-6.so` or `libclang.7.0.so`) cannot be found, an error will be thrown?

The only alternative I can think of that doesn't use the filename to check the version would be to link to each `libclang` library in the build script using `libloading` and attempting to load a function only present on versions of `libclang` greater than or equal to the requested version.

**Comment by KyleMayes** [comment]
Implemented as the `assert-minimum` Cargo feature in `v0.27.0`.
