### ISSUE TITLE
How to compile libclang version 6_0_0 to statically link

### ISSUE THREAD

**Issue by alickbass** [KyleMayes/clang-sys#80]
A noob question here. I would like to use your library together with clang-rs. However, due to some limitations, I need it statically linked. As you mentioned in the README, I would need to manually compile the libclang for version 6_0_0 to statically link it. Are there any good references of how to do it? Thanks in advance!

**Comment by KyleMayes** [comment]
The instructions [here](https://clang.llvm.org/get_started.html) describe how to build LLVM and Clang from source. I believe that static libraries are built by default as described [here](http://llvm.org/docs/CMake.html) under the `BUILD_SHARED_LIBS:BOOL` section.

**Comment by alickbass** [comment]
@KyleMayes thanks for a suggestion! For future reference, the needed flag was `LIBCLANG_BUILD_STATIC=ON`. Maybe would be helpful to add some doc somewhere how to compile from scratch needed version
