### ISSUE TITLE
Why is xcode-select searched before llvm-config on MacOSX ?

### ISSUE THREAD

**Issue by gnzlbg** [KyleMayes/clang-sys#87]
Why is `xcode-select` searched first for the path, and `llvm-config` second on MacOS X?  

If I have an LLVM compiled from source, and put it on my path, `llvm-config` will always return the correct result, but `xcode-select` will return the paths for some other LLVM (the one bundled with whatever SDK is active).

**Comment by KyleMayes** [comment]
I changed the order in `v0.28.0` so this might be fixed.
