### ISSUE TITLE
MSRV and history

### ISSUE THREAD

**Issue by stevenroose** [KyleMayes/clang-sys#94]
Is there a known MSRV? The only versions tested in CI seem `stable` and `1.36.0`. I also can't find anything in the changelog about MSRV updates.

It would be very helpful if the project was aware of the MSRV, enforced that in CI and would consider changes to that value as breaking changes to the lib and thus include them in the changelog and use breaking semver version bumps for it.

**Comment by stevenroose** [comment]
I noticed that support for rustc v1.31.0 was broken in a non-breaking semver update from `0.28.0` to `0.28.1`. It would be greatly appreciated it MSRV updates would be consider semver breaking in the future. Thanks!

**Comment by KyleMayes** [comment]
An MSRV has been added (1.36.0) and enforced with CI.
